name: Build with Google gcc and clang

on:
  workflow_dispatch:
jobs:
  building:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:          
       - name: git clone
         run: git clone --depth=1 https://github.com/Yaroslav51-dev/Vayu-kernel.git -b main $HOME/vayu
         
       - name: google clang
         run: git clone --depth=1 --single-branch https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r530567 -b 14.0 $HOME/clang

       - name: google gcc
         run: |
                 mkdir -p -v $HOME/gcc64
                 aria2c -o gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
                 tar -C $HOME/gcc64 -zxf gcc-aarch64.tar.gz
                 mkdir -p -v $HOME/gcc32
                 aria2c -o gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
                 tar -C $HOME/gcc32 -zxf gcc-arm.tar.gz
                 
       - name: build
         run: bash $HOME/vayu/build.sh
         
       - name: Upload image
         uses: actions/upload-artifact@v3
         with:
          name: Image
          path: $HOME/vayu/out/arch/arm64/boot/Image

       - name: Upload image
         uses: actions/upload-artifact@v3
         with:
          name: Image.gz
          path: $HOME/vayu/out/arch/arm64/boot/Image.gz          

       - name: Upload dtb
         uses: actions/upload-artifact@v3
         with:
          name: dtb
          path: $HOME/vayu/out/arch/arm64/boot/dtb

       - name: Upload dtb
         uses: actions/upload-artifact@v3
         with:
          name: dtbo.img
          path: $HOME/vayu/out/arch/arm64/boot/dtbo.img
