name: Build Kernel

on:
  workflow_dispatch:
jobs:
  building:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:     
       - name: echo 
         run: echo $HOME
       
       - name: git clone
         run: git clone --depth=1 https://github.com/Yaroslav51-dev/android_kernel_xiaomi_vayu-arrow.git -b main vayu
       
       - name: echo 
         run: git clone https://github.com/kdrag0n/proton-clang.git -b master --depth=1 clang
       
       - name: build
         run: cd vayu && bash build.sh
         
       - name: Upload image
         uses: actions/upload-artifact@v3
         with:
          name: Image
          path: /home/runner/work/kernel_build/kernel_build/vayu/out/arch/arm64/boot/Image

       - name: Upload image
         uses: actions/upload-artifact@v3
         with:
          name: Image.gz
          path: /home/runner/work/kernel_build/kernel_build/vayu/out/arch/arm64/boot/Image.gz
          

       - name: Upload dtb
         uses: actions/upload-artifact@v3
         with:
          name: dtb
          path: /home/runner/work/kernel_build/kernel_build/vayu/out/arch/arm64/boot/dtb

       - name: Upload dtb
         uses: actions/upload-artifact@v3
         with:
          name: dtbo.img
          path: /home/runner/work/kernel_build/kernel_build/vayu/out/arch/arm64/boot/dtbo.img
          
