name: Build with Google gcc and clang

on:
  workflow_dispatch:
jobs:
  building:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:          
       - name: git clone
         run: git clone --depth=1 https://github.com/Yaroslav51-dev/android_kernel_xiaomi_liuqin.git -b main $HOME/vayu

       - name: google clang and gcc
         run: |
                 git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r530567.git --depth=1 -b 14.0 $HOME/clang
                 git clone https://android.googlesource.com/platform/prebuilts/build-tools $HOME/build-tools --depth=1
                 git clone https://android.googlesource.com/platform/prebuilts/gas/linux-x86 $HOME/gas/linux-x86 --depth=1
                 export PATH="$HOME/clang/bin:$PATH"
                 export PATH=$HOMEtc/build-tools/path/linux-x86:$PATH
                 export PATH=$HOME/gas/linux-x86:$PATH
                 
       - name: build
         run: wget https://raw.githubusercontent.com/Yaroslav51-dev/kernel_build/main/script/build_google.sh -P $HOME/vayu && bash $HOME/vayu/build_google.sh

       - name: Upload image
         uses: actions/upload-artifact@v3
         with:
          name: Image
          path: /home/runner/vayu/out/arch/arm64/boot/Image         

       - name: Upload dtb
         uses: actions/upload-artifact@v3
         with:
          name: dtb
          path: /home/runner/vayu/out/arch/arm64/boot/dts/qcom/*.dtb

       - name: Upload dtbo
         uses: actions/upload-artifact@v3
         with:
          name: dtbo.img
          path: /home/runner/vayu/out/arch/arm64/boot/dtbo.img
