name: Build with Google gcc and clang

on:
  workflow_dispatch:
jobs:
  building:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:          
       - name: git clone
         run: git clone --depth=1 https://github.com/Yaroslav51-dev/android_kernel_xiaomi_liuqin.git -b main $HOME/vayu

       - name: google clang and gcc
         run: |
                 mkdir -p -v $HOME/gcc64
                 aria2c -o gcc-aarch64.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-14.0.0_r0.108.tar.gz
                 tar -C $HOME/gcc64 -zxf gcc-aarch64.tar.gz
                 mkdir -p -v $HOME/gcc32
                 aria2c -o gcc-arm.tar.gz https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/tags/android-14.0.0_r0.108.tar.gz
                 tar -C $HOME/gcc32 -zxf gcc-arm.tar.gz
                 git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r530567.git --depth=1 -b 14.0 $HOME/clang
                 export PATH="$HOME/gcc64/bin:$PATH"
                 export PATH="$HOME/gcc32/bin:$PATH"
                 export PATH="$HOME/clang/bin:$PATH"
                 
       - name: build
         run: wget https://raw.githubusercontent.com/Yaroslav51-dev/kernel_build/main/script/build_google.sh -P $HOME/vayu && bash $HOME/vayu/build_google.sh

       - name: Upload image
         uses: actions/upload-artifact@v3
         with:
          name: Image
          path: /home/runner/vayu/out/arch/arm64/boot/Image         

       - name: Upload dtb
         uses: actions/upload-artifact@v3
         with:
          name: dtb
          path: /home/runner/vayu/out/arch/arm64/boot/dts/qcom/*.dtb

       - name: Upload dtbo
         uses: actions/upload-artifact@v3
         with:
          name: dtbo.img
          path: /home/runner/vayu/out/arch/arm64/boot/dtbo.img
