name: Build mi kernel

on:
  workflow_dispatch:
jobs:
  building:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:          
       - name: git clone
         run: git clone --depth=1 https://github.com/Yaroslav51-dev/MiCode_Kernel_Vayu.git -b vayu-r-oss $HOME/vayu
         
       - name: google clang and gcc
         run: |
                 git clone https://github.com/blakbin/vayu_toolchain.git -b master $HOME/toolchain
                 export PATH="$HOME/toolchain/clang/LLVM-10.0.9/bin:$PATH"
                 export PATH="$HOME/toolchain/gcc/aarch64-linux-android-4.9/bin:$PATH"
                 
       - name: build
         run: wget https://raw.githubusercontent.com/Yaroslav51-dev/kernel_build/main/script/build_mi.sh -P $HOME/vayu && bash $HOME/vayu/build_mi.sh

       - name: Upload image
         uses: actions/upload-artifact@v3
         with:
          name: Image
          path: /home/runner/vayu/out/arch/arm64/boot/Image         

       - name: Upload dtb
         uses: actions/upload-artifact@v3
         with:
          name: dtb
          path: /home/runner/vayu/out/arch/arm64/boot/dts/qcom/*.dtb

       - name: Upload dtbo
         uses: actions/upload-artifact@v3
         with:
          name: dtbo.img
          path: /home/runner/vayu/out/arch/arm64/boot/dtbo.img
