name: Build with Neutron gcc and clang

on:
  workflow_dispatch:
jobs:
  building:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:          
       - name: git clone
         run: git clone --depth=1 https://github.com/Yaroslav51-dev/android_kernel_xiaomi_vayu-arrow.git -b main $HOME/vayu
         
       - name: google clang and gcc
         run: |
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git --depth=1 -b android-msm-coral-4.14-t-preview-2 $HOME/gcc64
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git --depth=1 -b android-msm-coral-4.14-t-preview-2 $HOME/gcc32
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r530567.git --depth=1 -b 14 $HOME/clang
          export PATH="$HOME/gcc64/bin:$PATH
          export PATH="$HOME/gcc32/bin:$PATH
          export PATH="$HOME/clang/bin:$PATH
                 
       - name: build
         run: bash $HOME/vayu/build.sh

       - name: Upload image
         uses: actions/upload-artifact@v3
         with:
          name: Image
          path: /home/runner/vayu/out/arch/arm64/boot/Image         

       - name: Upload dtb
         uses: actions/upload-artifact@v3
         with:
          name: dtb
          path: /home/runner/vayu/out/arch/arm64/boot/dts/qcom/*.dtb

       - name: Upload dtbo
         uses: actions/upload-artifact@v3
         with:
          name: dtbo.img
          path: /home/runner/vayu/out/arch/arm64/boot/dtbo.img
